desc "Deploy a new alpha build to Google Play"
lane :alpha do
  build_number = number_of_commits()
  Dir.chdir "../.." do
    sh("flutter", "packages", "get")
    sh("flutter", "clean")
    sh("flutter", "build", "appbundle", "--build-number=#{build_number}")
  end
  upload_to_play_store(track: 'alpha', aab: '../build/app/outputs/bundle/release/app-release.aab')
end

desc "Deploy a new beta build to Google Play"
lane :beta do
  build_number = number_of_commits()
  Dir.chdir "../.." do
    sh("flutter", "packages", "get")
    sh("flutter", "clean")
    sh("flutter", "build", "apk", "--build-number=#{build_number}")
  end
  firebase_app_distribution(
    app: "$System.env.FIREBASE_APP_ID",
    apk_path: '../build/app/outputs/apk/release/app-release.apk',
    service_credentials_file:'key.json',
    groups: "test"
  )
end