# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: My-flw

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
#       - run: cd android
#       - run: sh fastlane_install.sh
#         working-directory: android
#       - run: fastlane add_plugin firebase_app_distribution
#         working-directory: android
      - run: echo ${{ secrets.FIREBASE_CLI }} | base64 --decode > key.jks
        working-directory: android
#       - run: fastlane run update_fastlane
#         working-directory: android
      - run: fastlane beta
        working-directory: android
        env:
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}

