# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: My-flw

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: ls -s
      - run: sudo apt install ruby ruby-dev
      - run: sudo gem install fastlane
      - run: fastlane add_plugin firebase_app_distribution
      - run: echo ${{ secrets.FIREBASE_CLI }} | base64 --decode > key.jks
      - run: fastlane beta
        env:
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
