# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: My-flw

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: echo ${{ secrets.FIREBASE_CLI }} | base64 --decode > key.jks
        working-directory: android
      - run: gem install fastlane
        working-directory: android
      - run: sudo gem install fastlane-plugin-firebase_app_distribution
        working-directory: android
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: fastlane beta
        working-directory: android
        env:
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}

